### PR TITLE
Books refactor and test endpoint

### PR DESCRIPTION
**Pull request by ederic-oytas**
# Pull Request Template

## Description

This pull request:

- Refactors the API for the two `/books` endpoints into its own file: books.py.
- Refactors some tests for the API
- Adds a message to the `/api/test/` endpoint.

## Type of Change

Refactor

## Checklist

- [x] I have read the contributing guidelines.
- [x] I have followed the code style of this project.
- [x] I have added tests to cover my changes.
- [x] I have updated the documentation (if applicable).
- [x] My changes do not generate new warnings.

## Related Issue

#15

### CODE REVIEW

**Comment by LilAttacker** [comment]
Overall, everything looks good. The refactoring makes sense and helps to keep __main__.py from being bloated. I don't think this change was entirely necessary but not really against it either.

My only concern is the lack of documentation explaining anything. There is a single comment in the entirety of books.py and nothing explaining what's happening.

Even just some simple block comments at the top of the file and functions to explain the purpose/input/etc. would be pretty useful by itself. Otherwise this is fine.

**Review by David1000734 — APPROVED** [review]
Everything looks good. We are no longer using lazy loading and HTTP methods are specified so it is clear what we expect each from route. 

Only thing is that in the test_api.py file, it seems to be using and double quotation ( " ) and single quotation ( ' ) interchangeable in the client.post(...). Defaulting to one or the other for consistency would be nice.

**Comment by ederic-oytas** [comment]
Yes, we can address this issue by using the `black` formatter. We can use the `poe format` command as produced from #20.

**Review by LilAttacker — APPROVED** [review]
You know what, after re-reviewing this, I don't think this needs anything.

I completely overlooked several comments blocks and its honestly fine. Approved.

**Pull request merged**
