### PR TITLE
Added Settings Component

### PR DESCRIPTION
**Pull request by David1000734**
# Pull Request Template

## Description
Added the settings page as well the settings component. The component can be added easily by providing 4 required parameters which are, name, link to the page, description, followed by the icon. This will create the settings along with the margins followed by the other components as well; ensuring consistency from one setting to another. 

## Type of Change

- [ ] Bugfix
- [ X ] New Feature
- [ ] Documentation Update
- [ ] Other (please describe):

## Checklist

- [ X ] I have read the contributing guidelines.
- [ ] I have followed the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation (if applicable).
- [ ] My changes do not generate new warnings.

## Additional Notes
For some reason, the href in FooterNavBar has an error from TypeScrip saying 
"Type '"/setting"' is not assignable to type 'Href<"/setting">'.ts(2322)"
but everything still works.

### CODE REVIEW

**Comment by caesarx26** [comment]
For the settings component I recommend using svgs instead of pngs.

**Comment by MrSnoodle01** [comment]
I agree with Caesar that changing the pngs to svgs is a good idea. Another thing to note regarding this commit is that this also adds the universal colors in the tailwind config file. Everything else looks good though.

**Review by MrSnoodle01 — APPROVED** [review]

**Comment by caesarx26** [comment]
Try to fix the type issue if possible this is what chat gpt says:
https://chatgpt.com/share/671c4864-52d0-800a-8521-0cfc47bbce0c

**Review by caesarx26 — APPROVED** [review]
For the settings component I recommend using svgs instead of pngs. And you can add some temp pages of of the specific settings pages for now do not have to be styled

**Comment by LilAttacker** [comment]
Before this is merged, even though it already has two approvals, it needs to resolve its merge conflicts. Some stuff has changed and that needs to be checked to make sure everything still works.


Additionally, there are no comments! Anywhere! We need documentation! I feel it is unreasonable to expect everyone to just know what things do. If we review this in a month, we may have forgotten what this was exactly for and instead of reading some handy comments, we would be forced to dig through the code to see how it worked and go backwards from there.

Chatgpt suggested its own comments to SettingBar.tsx: https://chatgpt.com/share/67200490-3520-800f-8a57-05a6c4287937


Finally, I'm not entirely sure how relevant this is but this is what chatgpt said about your error you mentioned in the notes: https://chatgpt.com/share/6720050f-2694-800f-ab84-dcc7a41a36e7. Have a look and see if this could be what's causing it. Sorry I'm not familiar enough with the language to offer any real advice beyond that.

I'm not sure how comfortable I am with merging a guaranteed error into the project, so it would be greatly appreciated if this could be solved.


ALSO, no tests! Although now we assigned someone to write them, so maybe this doesn't need them just yet. But we really should be adding tests to features we intend to keep into the PR that implements them.

**Comment by David1000734** [comment]
Comments was added, changed SVG so that it can take height and width parameters as well. Also, that error about the setting's href just disappeared... So there is no errors on this branch.

**Comment by LilAttacker** [comment]
Thank you for adding comments, resolving the merge issue, and clarifying that the error you had has disappeared.

Slightly concerning that the error just went away, but its hopefully okay.

Your comments look good. I suppose its intentional that the icon files have no comments, but I will note that FooterNavBar.tsx also has no comments, and that looks a bit more substantial code wise. Please clarify if that is indeed intentional. Otherwise, I have no other issues with this.

**Pull request merged**
