### PR TITLE
Add Logging

### PR DESCRIPTION
**Pull request by ederic-oytas**
# Pull Request Template

## Description

This PR adds logging to the server. This can be used to how long each part of the endpoint takes.

Example output:

```
[2024-11-27 14:55:22,002] (INFO) books: Start /scan_cover
[2024-11-27 14:55:22,002] (INFO) books: START      Read image
[2024-11-27 14:55:22,100] (INFO) books: END   0.10s Read image 
[2024-11-27 14:55:22,146] (INFO) books: START      Recognize text using OCR
[2024-11-27 14:55:23,300] (WARNING) easyocr: Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
[2024-11-27 14:55:37,196] (INFO) books: END  15.05s Recognize text using OCR 
[2024-11-27 14:55:37,196] (INFO) books: START      Extract title and author using ChatGPT
[2024-11-27 14:55:38,695] (INFO) extraction: Success. Took 1 attempt(s).
[2024-11-27 14:55:38,696] (INFO) books: END   1.50s Extract title and author using ChatGPT
[2024-11-27 14:55:38,697] (INFO) books: START      Request info from Google Books
[2024-11-27 14:55:38,697] (INFO) google_books: Query: 'THE GIVER inauthor:LOIS LOWRY'
[2024-11-27 14:55:39,167] (INFO) books: END   0.47s Request info from Google Books 
[2024-11-27 14:55:39,172] (INFO) _internal: 127.0.0.1 - - [27/Nov/2024 14:55:39] "POST /books/scan_cover HTTP/1.1" 200 -
```

## Type of Change

- [ ] Bugfix
- [x] New Feature
- [ ] Documentation Update
- [ ] Other (please describe):

## Checklist

- [x] I have read the contributing guidelines.
- [x] I have followed the code style of this project.
- [x] I have added tests to cover my changes.
- [x] I have updated the documentation (if applicable).
- [x] My changes do not generate new warnings.

### CODE REVIEW

**Comment by MrSnoodle01** [comment]
I like this PR, being able to see exactly where the backend could be more optimized is very useful, especially for an app like this where we don't want the user to have to wait a long time to get results.

**Review by MrSnoodle01 — APPROVED** [review]

**Comment by ederic-oytas** [comment]
I also updated requirements.txt

**Review by David1000734 — APPROVED** [review]
Very useful functions since now we can cost-optimize which instances we should for the fastest time while keeping cost low

**Review by LilAttacker — APPROVED** [review]
Thank you for implementing this feature so quickly!
Looks good! Approved!

EDIT: Keeping the issue open so Caesar has a chance to up the number of reviews.

**Pull request merged**
