### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ederic-oytas**
# Pull Request Template

## Description

Major Changes:
- /scan_shelf now uses OCR to recognize the image at angles 0, 90, and 270 degrees. This helps with books which are sideways.
- Reworked /scan_shelf and /scan_cover to not use `inauthor` anymore.
  - This increased the number of results from Google Books, but I believe this is good in cases where the OCR-ChatGPT part of the pipeline fails to identify the author.
- Made filtering by ISBN able to be toggled. This can be toggled by the `FILTER_ISBN` environment variable (non-zero value to turn it on, 0 to turn it off). Defaults to `1` when no value is given.

Minor changes:
- More logging messages
- Fixed some scripts
- Fixed some ai-gen comments
- Added some docstrs
- Added a section on environment variables in server/README.md

## Type of Change

- [x] Bugfix
- [x] New Feature
- [x] Documentation Update
- [ ] Other (please describe):

## Checklist

- [x] I have read the contributing guidelines.
- [x] I have followed the code style of this project.
- [x] I have added tests to cover my changes.
- [x] I have updated the documentation (if applicable).
- [x] My changes do not generate new warnings.

### CODE REVIEW

**Comment by ederic-oytas** [comment]
I've made filtering by ISBN togglable.

**Review by LilAttacker — APPROVED** [review]
Having a look around, everything looks good. Test coverage is good, logs look good, nothing stands out to me that might need fixing.

Approved.

**Review by MrSnoodle01 — APPROVED** [review]
I think that everything looks good, you added more tests which is always a good thing and increasing OCR accuracy is great.

**Review by caesarx26 — APPROVED** [review]
Everything looks good!

**Pull request merged**
